var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];if(!(f in c))return;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var f=a.split(".");a=1===f.length;d=f[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var k=0;k<f.length-1;k++){var e=f[k];if(!(e in d))return;d=d[e]}f=f[f.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[f]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[f]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+c+"$"+f),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[f],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var f=d.value}catch(k){return this.context_.yieldAllIterator_=null,this.context_.throw_(k),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(d){return a.next(d)}function c(d){return a["throw"](d)}return new Promise(function(d,f){function k(e){e.done?d(e.value):Promise.resolve(e.value).then(b,c).then(k,f)}k(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(k,e){this.$jscomp$symbol$id_=k;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:e})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,f=function(k){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new b(c+(k||"")+"_"+d++,k)};return f},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(e){return e instanceof f?e:new f(function(g,h){g(e)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(e){if(null==this.batch_){this.batch_=[];var g=this;this.asyncExecuteFunction(function(){g.executeBatch_()})}this.batch_.push(e)};
var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(e){d(e,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var e=this.batch_;this.batch_=[];for(var g=0;g<e.length;++g){var h=e[g];e[g]=null;try{h()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(e){this.asyncExecuteFunction(function(){throw e;})};var f=function(e){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var g=this.createResolveAndReject_();
try{e(g.resolve,g.reject)}catch(h){g.reject(h)}};f.prototype.createResolveAndReject_=function(){function e(l){return function(m){h||(h=!0,l.call(g,m))}}var g=this,h=!1;return{resolve:e(this.resolveTo_),reject:e(this.reject_)}};f.prototype.resolveTo_=function(e){if(e===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof f)this.settleSameAsPromise_(e);else{a:switch(typeof e){case "object":var g=null!=e;break a;case "function":g=!0;break a;default:g=!1}g?this.resolveToNonPromiseObj_(e):
this.fulfill_(e)}};f.prototype.resolveToNonPromiseObj_=function(e){var g=void 0;try{g=e.then}catch(h){this.reject_(h);return}"function"==typeof g?this.settleSameAsThenable_(g,e):this.fulfill_(e)};f.prototype.reject_=function(e){this.settle_(2,e)};f.prototype.fulfill_=function(e){this.settle_(1,e)};f.prototype.settle_=function(e,g){if(0!=this.state_)throw Error("Cannot settle("+e+", "+g+"): Promise already settled in state"+this.state_);this.state_=e;this.result_=g;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};f.prototype.scheduleUnhandledRejectionCheck_=function(){var e=this;d(function(){if(e.notifyUnhandledRejection_()){var g=$jscomp.global.console;"undefined"!==typeof g&&g.error(e.result_)}},1)};f.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var e=$jscomp.global.CustomEvent,g=$jscomp.global.Event,h=$jscomp.global.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof e?e=new e("unhandledrejection",{cancelable:!0}):
"function"===typeof g?e=new g("unhandledrejection",{cancelable:!0}):(e=$jscomp.global.document.createEvent("CustomEvent"),e.initCustomEvent("unhandledrejection",!1,!0,e));e.promise=this;e.reason=this.result_;return h(e)};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var e=0;e<this.onSettledCallbacks_.length;++e)k.asyncExecute(this.onSettledCallbacks_[e]);this.onSettledCallbacks_=null}};var k=new b;f.prototype.settleSameAsPromise_=function(e){var g=this.createResolveAndReject_();
e.callWhenSettled_(g.resolve,g.reject)};f.prototype.settleSameAsThenable_=function(e,g){var h=this.createResolveAndReject_();try{e.call(g,h.resolve,h.reject)}catch(l){h.reject(l)}};f.prototype.then=function(e,g){function h(n,p){return"function"==typeof n?function(q){try{l(n(q))}catch(r){m(r)}}:p}var l,m,t=new f(function(n,p){l=n;m=p});this.callWhenSettled_(h(e,l),h(g,m));return t};f.prototype["catch"]=function(e){return this.then(void 0,e)};f.prototype.callWhenSettled_=function(e,g){function h(){switch(l.state_){case 1:e(l.result_);
break;case 2:g(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?k.asyncExecute(h):this.onSettledCallbacks_.push(h);this.isRejectionHandled_=!0};f.resolve=c;f.reject=function(e){return new f(function(g,h){h(e)})};f.race=function(e){return new f(function(g,h){for(var l=$jscomp.makeIterator(e),m=l.next();!m.done;m=l.next())c(m.value).callWhenSettled_(g,h)})};f.all=function(e){var g=$jscomp.makeIterator(e),h=g.next();return h.done?c([]):new f(function(l,
m){function t(q){return function(r){n[q]=r;p--;0==p&&l(n)}}var n=[],p=0;do n.push(void 0),p++,c(h.value).callWhenSettled_(t(n.length-1),m),h=g.next();while(!h.done)})};return f},"es6","es3");
var net={56:"Binance Smart Chain (BSC) Mainnet",97:"Binance Smart Chain (BSC) Testnet",108:"ThunderCore (TT) Mainnet",264:"ThunderCore (TT) Mainnet",18:"ThunderCore (TT) Testnet",137:"Polygon (MATIC) Mainnet",80001:"Polygon (MATIC) Mumbai Testnet"},altnet={108:264,264:108},currency={56:"BNB",97:"BNB",108:"TT",264:"TT",18:"TT",137:"MATIC",80001:"MATIC"},tracker={56:"https://bscscan.com/",97:"https://testnet.bscscan.com/",108:"https://viewblock.io/thundercore/",264:"https://viewblock.io/thundercore/",
18:"https://scan-testnet.thundercore.com/",137:"https://explorer-mainnet.maticvigil.com/",80001:"https://explorer-mumbai.maticvigil.com/"},trackerToken={56:"token/",97:"token/",108:"https://viewblock.io/thundercore/address/",264:"https://viewblock.io/thundercore/address/",18:"https://scan-testnet.thundercore.com/address/",137:"https://explorer-mainnet.maticvigil.com/address/",80001:"https://explorer-mumbai.maticvigil.com/address/"},trackerAddress={56:"address/",97:"address/",108:"address/",264:"address/",
18:"address/",137:"address/",80001:"address/"},contractAddress,tokenAddress,decimals,name,symbol,rate,sc,hc,min,max,start,starttime,end,endtime,lpper,lprate,lpun,lpuntime,ver,raised,raisedd,st,status,presale,presaleSign,contractToken,balance,myRemaining=Number(max),abiPresale=[{inputs:[{internalType:"address",name:"_tokenAddress",type:"address"},{internalType:"uint256[]",name:"_params",type:"uint256[]"},{internalType:"bool",name:"_auto",type:"bool"},{internalType:"uint256",name:"_edge",type:"uint256"}],
stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!1,internalType:"address",name:"buyer",type:"address"},{indexed:!1,internalType:"uint256",name:"amount",type:"uint256"}],name:"Contribution",type:"event"},{inputs:[],name:"autoFinalize",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],name:"balances",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",
type:"function"},{inputs:[],name:"buyToken",outputs:[],stateMutability:"payable",type:"function"},{inputs:[],name:"canClaim",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"canFinalize",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"canRefund",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"cancel",outputs:[],stateMutability:"nonpayable",
type:"function"},{inputs:[],name:"canceled",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_qty",type:"uint256"}],name:"checkAmount",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_payment",type:"uint256"}],name:"checkChange",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",
name:"_payment",type:"uint256"}],name:"checkQty",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"checkStatus",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"claim",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"delay",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"endTime",
outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"ended",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"finalize",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"finalized",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"hardcap",outputs:[{internalType:"uint256",name:"",type:"uint256"}],
stateMutability:"view",type:"function"},{inputs:[],name:"hardcapOk",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"listingPercent",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"listingRate",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"lpUnlock",outputs:[{internalType:"uint256",name:"",type:"uint256"}],
stateMutability:"view",type:"function"},{inputs:[],name:"myTokens",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"purchaseLimit",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"purchaseMin",outputs:[{internalType:"uint256",name:"",type:"uint256"}],
stateMutability:"view",type:"function"},{inputs:[],name:"rate",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"refund",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"_refundable",type:"address"}],name:"refundByAdmin",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"remaining",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},
{inputs:[{internalType:"address",name:"_buyer",type:"address"}],name:"remainingLimit",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"router",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"sandwichAdmin",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"sandwichBNB",outputs:[{internalType:"address",name:"",
type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"sandwichEdge",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"sandwichTkn",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"softcap",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],name:"spendings",
outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"startTime",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"tokenAddress",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"tokenBalance",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalRaised",
outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSold",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"unclaimed",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"uniswapV2Pair",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"uniswapV2Router",
outputs:[{internalType:"contract IUniswapV2Router02",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdrawBNB",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"_address",type:"address"}],name:"withdrawCustomToken",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"withdrawLiquidity",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_quantity",type:"uint256"}],
name:"withdrawTokens",outputs:[],stateMutability:"nonpayable",type:"function"},{stateMutability:"payable",type:"receive"}],abiToken=[{inputs:[{internalType:"string",name:"_name",type:"string"},{internalType:"string",name:"_symbol",type:"string"},{internalType:"uint256",name:"_dec",type:"uint256"},{internalType:"uint256",name:"_supply",type:"uint256"},{internalType:"uint256",name:"_tax1",type:"uint256"},{internalType:"address",name:"_address1",type:"address"},{internalType:"uint256",name:"_tax2",type:"uint256"},
{internalType:"address",name:"_address2",type:"address"},{internalType:"uint256",name:"_deflation",type:"uint256"},{internalType:"uint256",name:"_minSupply",type:"uint256"},{internalType:"address",name:"_owner",type:"address"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"owner",type:"address"},{indexed:!0,internalType:"address",name:"spender",type:"address"},{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Approval",
type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"from",type:"address"},{indexed:!0,internalType:"address",name:"to",type:"address"},{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Transfer",type:"event"},{inputs:[],name:"addressTax1",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"addressTax2",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},
{inputs:[{internalType:"address",name:"owner",type:"address"},{internalType:"address",name:"spender",type:"address"}],name:"allowance",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"spender",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"approve",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"owner",
type:"address"}],name:"balanceOf",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"burnt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"decimals",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"deflation",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},
{inputs:[],name:"initialSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"minSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"name",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",type:"function"},{inputs:[],name:"symbol",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",type:"function"},{inputs:[],
name:"tax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"tax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalTax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalTax2",
outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"transfer",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"from",type:"address"},{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"transferFrom",
outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"}],network,curnet,mainnetAlt,usenet,myAddress,signer,provider,canClaim,canRefund,up;$(function(){getUrlParams();getQR();window.ethereum?(loadData(),connect()):loadData()});
function loadData(){$("#addressPresale").html('<a title="View on explorer" target="_blank" href="'+tracker[usenet]+trackerAddress[usenet]+contractAddress+'">'+contractAddress+"</a>");$("#usenet").html(net[usenet]);$("#usenet1").html(net[usenet]);$.ajax({type:"get",url:"/php/load.php",data:{net:usenet,contract:contractAddress},contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,success:function(a){return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){$.each(a,function(c,
d){tokenAddress=d.t_add;$("#tokenAddress").html('<a title="View on explorer" target="_blank" href="'+tracker[usenet]+trackerToken[usenet]+tokenAddress+'">'+tokenAddress+"</a>");name=d.t_name;$("#tokenName").html(name);symbol=d.t_sym;$(".tokenSymbol").html(symbol);decimals=d.t_dec;rate=d.rate;$("#rate").html(rate);sc=d.sc;$("#sc").html(sc);hc=d.hc;$(".hc").html(hc);min=d.min;$("#min").html(min);max=d.max;$("#max").html(max);start=d.start;starttime=new Date(1E3*Number(start));$("#start").html(starttime);
end=d.end;endtime=new Date(1E3*Number(end));$("#end").html(endtime);lpper=d.lpper;$("#lpper").html(lpper);lprate=d.lprate;$("#lprate").html(lprate);lpun=d.lpun;lpuntime=new Date(1E3*Number(lpun));$("#lpun").html(lpuntime);fin=d.fin;delay=d.delay;1==fin?$("#final").html("Automatic, within "+Number(delay)/3600+" hours after the presale ends successfully or hard cap is reached"):$("#final").html("Manual (automatically finalized if you do not finalize it within 24h after the presale ends successfully or hard cap is reached)");
ver=d.ver;1==ver?$("#ver").html('<span class="img-verify"><img src="/images/verified-img.png" alt="Verified"></span> verified - the token was minted by Sandwich'):$("#ver").html("");if(d.logo&&""!=d.logo){var f=new Image;f.onload=function(){$("#logo").attr("src",d.logo)};f.onerror=function(){$("#logo").attr("src","/images/sandwichholder.png")};f.src=d.logo}else $("#logo").attr("src","/images/sandwichholder.png");$("#www").attr("href",d.www);$("#telegram").attr("href",d.tg);$("#twitter").attr("href",
d.tw);$("#facebook").attr("href",d.fb);$("#link").attr("href",d.link);$("#description").html(d.descr);if(!st&&!raised)if(raised=d.raised,$("#raised").html(raised),f=Number(raised)/Number(Number(hc)/100),$("#progress").css("width",f+"%"),st=d.st,4==Number(st))status="Canceled",$("#chk").prop("checked",!1),$("#status").html("Canceled"),$("#timer").hide();else if(3==Number(st))status="Finalized",$("#chk").prop("checked",!1),$("#status").html("Finalized"),$("#timer").hide();else if(2==Number(st))status=
"Fail",$("#chk").prop("checked",!1),$("#status").html("Failed"),$("#timer").hide();else if(1==Number(st))status="Success",$("#chk").prop("checked",!1),$("#status").html("Ended successfully"),$("#timer").hide();else if(0==Number(st)&&Date.now()<1E3*Number(start)){status="Upcoming";$("#chk").prop("checked",!1);$("#status").html("Starts in");$("#timer").show();var k=setInterval(function(){var g=1E3*Number(start)-Date.now();dhms(g);0>g&&(clearInterval(k),loadData())},1E3)}else if(0==Number(st)&&Date.now()>
1E3*Number(start)&&Date.now()<1E3*Number(end)){status="Live";$("#chk").prop("checked",!0);$("#status").html("Ends in");$("#timer").show();var e=setInterval(function(){var g=1E3*Number(end)-Date.now();dhms(g);0>g&&(clearInterval(e),loadData())},1E3)}else status="Unknown",$("#chk").prop("checked",!1),$("#status").html("Unknown status"),$("#timer").hide()});b.jumpToEnd()})},error:function(a){}})}
function updateStatus(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){window.ethereum&&(up=setInterval(update,1E4));a.jumpToEnd()})}
function myData(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return window.ethereum&&myAddress?c.yield(presale.spendings(myAddress),3):c.jumpTo(0);if(4!=c.nextAddress)return a=c.yieldResult,mySpent=ethers.utils.formatEther(a),$("#mySpendings").html(Number(mySpent)),myRemaining=Number(max)-Number(mySpent),c.yield(presale.myTokens({from:myAddress}),4);b=c.yieldResult;$("#myUnclaimed").html(Number(ethers.utils.formatUnits(b,decimals)));canClaim&&0<Number(b)?
$("#claim").prop("disabled",!1):$("#claim").prop("disabled",!0);canRefund&&0<Number(a)?$("#refund").prop("disabled",!1):$("#refund").prop("disabled",!0);$("#mytokensarea").show();$("#loading").hide();c.jumpToEnd()})}
function update(){var a,b,c,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:return presale=new ethers.Contract(contractAddress,abiPresale,provider),presaleSign=presale.connect(signer),f.yield(presale.totalRaised(),2);case 2:return raisedd=f.yieldResult,raised=ethers.utils.formatEther(raisedd),f.yield(presale.checkStatus(),3);case 3:return st=f.yieldResult,$("#raised").html(Number(raised)),a=Number(hc)/100,b=Number(raised)/Number(a),$("#progress").css("width",
b+"%"),4==Number(st)?(status="Canceled",$("#chk").prop("checked",!1),$("#status").html("Canceled"),$("#timer").hide()):3==Number(st)?(status="Finalized",$("#chk").prop("checked",!1),$("#status").html("Finalized"),$("#timer").hide()):2==Number(st)?(status="Fail",$("#chk").prop("checked",!1),$("#status").html("Failed"),$("#timer").hide()):1==Number(st)?(status="Success",$("#chk").prop("checked",!1),$("#status").html("Ended successfully"),$("#timer").hide()):0==Number(st)&&Date.now()<1E3*Number(start)?
(status="Upcoming",$("#chk").prop("checked",!1),$("#status").html("Starts in"),$("#timer").show(),c=setInterval(function(){var k=1E3*Number(start)-Date.now();dhms(k);0>k&&(clearInterval(c),loadData())},1E3)):0==Number(st)&&Date.now()>1E3*Number(start)&&Date.now()<1E3*Number(end)?(status="Live",$("#chk").prop("checked",!0),$("#status").html("Ends in"),$("#timer").show(),d=setInterval(function(){var k=1E3*Number(end)-Date.now();dhms(k);0>k&&(clearInterval(d),loadData())},1E3)):(status="Unknown",$("#chk").prop("checked",
!1),$("#status").html("Unknown status"),$("#timer").hide()),f.yield(presale.canClaim(),4);case 4:return canClaim=f.yieldResult,f.yield(presale.canRefund(),5);case 5:(canRefund=f.yieldResult)?($("#refund").show(),$("#claim").hide()):($("#refund").hide(),$("#claim").show()),$.ajax({type:"post",url:"/php/update.php",data:{net:usenet,contract:contractAddress,raised:Number(raised),status:Number(st)},success:function(k){console.log("Data updated ",k)},error:function(k){console.log("Error updating ",k)}}),
myData(),0!=Number(st)&&(clearInterval(up),loadData(),myData()),f.jumpToEnd()}})}function connect(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){provider=new ethers.providers.Web3Provider(window.ethereum,"any");provider.on("network",function(b,c){c&&getNetwork()});ethereum.on("accountsChanged",function(b){getNetwork()});ethereum.on("connect",function(b){getNetwork()});getNetwork();a.jumpToEnd()})}$("#connect").click(connectMe);$("#connect1").click(connectMe);
function connectMe(){var a,b,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(1==d.nextAddress){if(!window.ethereum)return $("#nometamask").fadeIn(1E3).fadeOut(1E3),d.jumpTo(0);d.setCatchFinallyBlocks(3);return d.yield(ethereum.request({method:"eth_requestAccounts"}),5)}if(3!=d.nextAddress)return a=d.yieldResult,(b=a[0])&&getAddress(),d.leaveTryBlock(0);c=d.enterCatchBlock();console.error(c);d.jumpToEnd()})}
function getNetwork(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(provider.getNetwork(),2);network=a.yieldResult;curnet=network.chainId;curnet==usenet||curnet==altnet[usenet]?($("#curnet").html(net[curnet]),getAddress(),updateStatus()):($("#curnet").html('<span class="err">Please use '+net[usenet]+"</span>"),$("#myAddr").html(""),$("#myarea").hide(),$("#buyarea").hide(),$("#nomyarea").show());a.jumpToEnd()})}
function getAddress(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){switch(b.nextAddress){case 1:return signer=provider.getSigner(),b.setCatchFinallyBlocks(2),b.yield(signer.getAddress(),4);case 4:myAddress=b.yieldResult;b.leaveTryBlock(3);break;case 2:a=b.enterCatchBlock(),console.log(a),!myAddress&&window.ethereum&&ethereum.request({method:"eth_requestAccounts"}).then(getNetwork);case 3:$("#myAddr").html(myAddress),myAddress?($("#errors").html(""),$(".connect").html(myAddress.substr(0,
4)+"..."+myAddress.substr(-4,4)),$(".connect").attr("title",myAddress),$("#myarea").show(),$("#buyarea").show(),$("#nomyarea").hide()):($("#errors").html("Please connect to your wallet!"),$(".connect").html("Connect wallet"),$(".connect").attr("title","Connect wallet"),$("#myarea").hide(),$("#buyarea").hide(),$("#nomyarea").show()),b.jumpToEnd()}})}
function init(){var a,b,c,d,f,k,e,g;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){switch(h.nextAddress){case 1:return $("#addressPresale").html('<a title="View on explorer" target="_blank" href="'+tracker[curnet]+trackerAddress[curnet]+contractAddress+'">'+contractAddress+"</a>"),$("#adminContract").html(contractAddress),presale=new ethers.Contract(contractAddress,abiPresale,provider),h.yield(presale.tokenAddress(),2);case 2:return tokenAddress=h.yieldResult,a=new ethers.Contract(tokenAddress,
abiToken,provider),h.yield(a.name(),3);case 3:return b=h.yieldResult,h.yield(a.symbol(),4);case 4:return symbol=h.yieldResult,h.yield(a.decimals(),5);case 5:return decimals=h.yieldResult,c=ethers.utils.formatUnits(lockedtokens,decimals),d=c+symbol,h.yield(presale.locked(),6);case 6:return f=h.yieldResult,h.yield(presale.UnlockTime(),7);case 7:k=h.yieldResult,e=new Date(1E3*Number(k)),g=f?'<span style="color: red">Locked &#128274;</span>':'<span style="color: green">Unlocked &#128275;</span>',$("#addressToken").html('<a title="View on explorer" target="_blank" href="'+
tracker[curnet]+trackerToken[curnet]+tokenAddress+'">'+tokenAddress+"</a>"),$("#name").html(b),$(".symbol").html(symbol),$("#balance").html(d),$("#date").html(e),$("#status").html(g),h.jumpToEnd()}})}function getUrlParams(){var a=new URLSearchParams(window.location.search);!0===a.has("id")&&""!==a.get("id")&&ethers.utils.isAddress(a.get("id"))&&(contractAddress=a.get("id"));!0===a.has("net")&&""!==a.get("net")&&(usenet=a.get("net"))}
function dhms(a){days=Math.floor(a/864E5);daysms=a%864E5;hours=Math.floor(daysms/36E5);hoursms=a%36E5;minutes=Math.floor(hoursms/6E4);minutesms=a%6E4;sec=Math.floor(minutesms/1E3);$("#timerD").html(days+"d");$("#timerH").html(hours+"h");$("#timerM").html(minutes+"m");$("#timerS").html(sec+"s")}
$("#buy").click(function(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress){a=$("#amount").val();if(!(""!==a&&0<Number(a)))return c.jumpTo(0);b=ethers.utils.parseEther(a);return c.yield(presaleSign.buyToken({value:b}),3)}if(4!=c.nextAddress)return tx=c.yieldResult,c.yield(tx.wait(),4);update();myData();loadData();c.jumpToEnd()})});
$("#claim").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return myAddress?a.yield(presaleSign.claim(),3):a.jumpTo(0);if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);update();myData();a.jumpToEnd()})});
$("#refund").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return myAddress?a.yield(presaleSign.refund(),3):a.jumpTo(0);if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);update();myData();a.jumpToEnd()})});$("#amount").change(function(){var a=$("#amount").val();Number(a)>Number(myRemaining)?$("#amount").val(Number(myRemaining)):0>Number(a)&&$("#amount").val(0)});
function getQR(){var a=encodeURIComponent(contractAddress);$("#saleqr").attr("src","/php/qr.php?data="+a)};